# docker-compose -f ./docker-compose-mkdocs-serve.yaml up --build
version: "2.4"
services:
  docs:
    build:
      context: .
      dockerfile: docs.dockerfile
    environment:
      - THEME_DIR=material
    volumes:
      - .:/main
    ports:
      - 80:80
    command:
      - bash
      - -c
      - |
        pwd
        mkdocs --version
        mkdocs serve -a 0.0.0.0:80
        # tail -f /dev/null
