# ---------------------- PROJECT SPECIFIC ---------------------------

site_name: DataJoint Documentation
site_url: http://localhost/docs
repo_name: datajoint-company/datajoint-docs
repo_url: https://github.com/datajoint-company/datajoint-docs
nav:
  - Welcome: index.md
  - Core:
    - Overview: core/index.md
    - Concepts:
      - Mantra: core/concepts/mantra.md
      - Getting Started:
        - First Steps: core/concepts/getting-started/index.md
        - Data Pipelines: core/concepts/getting-started/data-pipelines.md
        - Table Definitions: core/concepts/getting-started/table-definitions.md
        - Diagrams: core/concepts/getting-started/diagrams.md
        - Dependencies: core/concepts/getting-started/dependencies.md
      - Query Language:
        - Data Types: core/concepts/query-lang/data-types.md
        - Query Objects: core/concepts/query-lang/query-objs.md
        - Operators:  core/concepts/query-lang/operators.md
        - Common Commands: core/concepts/query-lang/common-commands.md
        - Primary Key: core/concepts/query-lang/primary-key.md
        - Normalization: core/concepts/query-lang/normalization.md
      - Reproducibility:
        - Table Tiers: core/concepts/reproduce/table-tiers.md
        - Make Methods: core/concepts/reproduce/make-method.md
      - Referential Integrity:
        - Query Backend: core/concepts/ref-integrity/query-backend.md
        - Distributed Computing: core/concepts/ref-integrity/distributed-computing.md
        - Relational Databases: core/concepts/ref-integrity/relational-databases.md
      - Glossary: core/glossary.md
      - FAQ: core/faq.md
  - Elements:
    - Overview: elements/index.md
    - Concepts: elements/concepts.md
    - User Guide: elements/user-guide.md
    - Developer Guide: elements/developer-guide.md
    - Management:
        - Plan: elements/management/plan.md
        - Team: elements/management/team.md
        - Governance: elements/management/governance.md
        - Selection: elements/management/selection.md
        - Quality Assurance: elements/management/quality-assurance.md
        - Outreach: elements/management/outreach.md
        - Adopt: elements/management/adopt.md
  - Works:
    - Overview: works/index.md
  - Projects: projects.md
  - Publications: publications.md
  - Citation: citation.md
  - Community:
    - Support: community/support.md
    - Events: community/events.md
    - Contribute: community/contribute.md
    - Licenses: community/licenses.md
    - History: community/history.md
    - Partnerships:
      - NWB: community/partnerships/nwb.md
      - DANDI: community/partnerships/dandi.md
      - Suite2p: community/partnerships/suite2p.md
      - Facemap: community/partnerships/facemap.md
      - INCF: community/partnerships/incf.md

# ---------------------------- STANDARD -----------------------------

docs_dir: ./src
edit_uri: ./edit/main/src
theme:
  font:
    text: Roboto Slab
    code: Source Code Pro
  name: material
  custom_dir: src/.overrides
  icon:
    logo: main/company-logo
  favicon: assets/images/company-logo-blue.png
  features:
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: datajoint
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - redirects:
      redirect_maps:
        "index.md": "welcome.md"
  - exclude:
      glob:
        - archive/*
        - images/*md
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      options:
        custom_icons:
          - .overrides/.icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mdx_truly_sane_lists
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.details: # permit folded <details> blocks via `??? note "Title"` format
  - pymdownx.snippets # Allows including file snippets e.g. --8<-- "; src/file.md"
  - pymdownx.magiclink
extra:
  generator: false # Disable watermark
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike
  social:
    - icon: main/company-logo
      link: https://www.datajoint.com
      name: DataJoint
    - icon: fontawesome/brands/slack
      link: https://datajoint.slack.com
      name: Slack
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datajoint
      name: LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/datajoint
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/datajoint
      name: GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/datajoint
      name: DockerHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/datajointbot
      name: PyPI
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/questions/tagged/datajoint
      name: StackOverflow
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCdeCuFOTCXlVMRzh6Wk-lGg
      name: YouTube
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - https://js-na1.hs-scripts.com/23133402.js  # HubSpot chatbot
